Add a Docker Compose example
High-Performance-IO/capio pull request #46
Opened 2023-12-28 13:16 UTC by GlassOfWhiskey

This commit configures the `Dockerfile` to set up and run an SSHD server to allow MPI connections. Plus, it adds an example that uses `docker compose` to set up a local distributed environment for development purposes.

2024-01-13 22:36 UTC, marcoSanti requested changes
When capio server is launched in background, output of capio command should be redirected to a file so that the output is not lost

2024-01-14 08:41 UTC, GlassOfWhiskey commented
> When capio server is launched in background, output of capio command should be redirected to a file so that the output is not lost

Added two server-specific output files named `server_${OMPI_COMM_WORLD_RANK}.out`

2024-01-14 08:44 UTC, marcoSanti reviewed
Approved :+1:

2024-01-14 08:44 UTC, marcoSanti approved these changes

2024-01-14 08:45 UTC, merged